import Head from 'next/head'
import classes from 'src/styles/Home.module.css'
import { Header } from 'src/components/Header'
import { Main } from 'src/components/Main'
import { Footer } from 'src/components/Footer'

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Main page="index" />
      <Footer />
    </div>
  )
}
