import Head from 'next/head'
import classes from 'src/styles/Home.module.css'
import { Header } from 'src/components/Header'
import { Main } from 'src/components/Main'
import { Footer } from 'src/components/Footer'
import { useCallback, useEffect } from 'react'

export default function Home() {
  const handleClick = useCallback((e) => {
    e.preventDefault();
    alert('sss');
  }, [])
  // コンポーネントがマウントされるときに読み込まれる
  useEffect(() => {
    console.log("マウント")
    document.body.style.backgroundColor = "lightblue";
    // リターン以後はアンマウントの際の処理を書く
    return () => {
      console.log("アンマウント")
      document.body.style.backgroundColor = "";
    }
  }, [])
  return (
    <div className={classes.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <a href="/about" onClick={handleClick}>ボタン</a>
      <Main page="index" />
      <Footer />
    </div>
  )
}
